<<<<<<< HEAD
CREATE TABLE "BANCO"."BANCO"(
    "ID" NUMBER NOT NULL,
    "NOMBRE" VARCHAR2(50 BYTE) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY("ID")
);

CREATE TABLE "BANCO"."USUARIO"(
    "ID" NUMBER NOT NULL,
    "NOMBRE" VARCHAR2(50 BYTE) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY("ID")
);

CREATE TABLE "BANCO"."CUENTA" (
	"ID" NUMBER NOT NULL, 
	"TIPO" VARCHAR2(20 BYTE) NOT NULL, 
	"BANCO_ID" NUMBER NOT NULL, 
	"USUARIO_ID" NUMBER NOT NULL, 
	"SALDO" FLOAT(126) DEFAULT 0 NOT NULL, 
    PRIMARY KEY("ID")
);

CREATE TABLE "BANCO"."MOVIMIENTO" (	
	"ID" NUMBER NOT NULL, 
	"CUENTA_ID" NUMBER NOT NULL, 
	"FECHA" DATE NOT NULL, 
	"SALDO_ANTERIOR" FLOAT(126) NOT NULL, 
	"SALDO_NUEVO" FLOAT(126) NOT NULL, 
	"MONTO" FLOAT(126) NOT NULL, 
	"TIPO_MOVIMIENTO" VARCHAR2(20 BYTE) NOT NULL, 
    PRIMARY KEY("ID")
);

alter table CUENTA
  add constraint FK_CUENTA_BANCO
  foreign key (BANCO_ID)
  references BANCO (ID);
  
alter table CUENTA
  add constraint FK_CUENTA_USUARIO
  foreign key (USUARIO_ID)
  references USUARIO(ID);

alter table MOVIMIENTO
  add constraint FK_MOVIMIENTO_CUENTA
  foreign key (CUENTA_ID)
  references CUENTA(ID);


CREATE SEQUENCE "BANCO"."BAN_SEQ" 
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1
    NOORDER NOCYCLE;
    
    create or replace TRIGGER ban_bir 
BEFORE INSERT ON BANCO 
FOR EACH ROW

BEGIN
  SELECT ban_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;


CREATE SEQUENCE "BANCO"."CUE_SEQ" 
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1
    NOORDER NOCYCLE;
    
    create or replace TRIGGER cue_bir 
BEFORE INSERT ON CUENTA 
FOR EACH ROW

BEGIN
  SELECT cue_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;



CREATE SEQUENCE "BANCO"."MOV_SEQ" 
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1
    NOORDER NOCYCLE;
    
    create or replace TRIGGER usu_bir 
BEFORE INSERT ON MOVIMIENTO 
FOR EACH ROW

BEGIN
  SELECT mov_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;


CREATE SEQUENCE "BANCO"."USU_SEQ" 
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1
    NOORDER NOCYCLE;
    
    create or replace TRIGGER usu_bir 
BEFORE INSERT ON USUARIO 
FOR EACH ROW

BEGIN
  SELECT usu_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
=======
CREATE TABLE "BANCO"."BANCO"(
    "ID" NUMBER NOT NULL,
    "NOMBRE" VARCHAR2(50 BYTE) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY("ID")
);

CREATE TABLE "BANCO"."USUARIO"(
    "ID" NUMBER NOT NULL,
    "NOMBRE" VARCHAR2(50 BYTE) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY("ID")
);

CREATE TABLE "BANCO"."CUENTA" (
	"ID" NUMBER NOT NULL, 
	"TIPO" VARCHAR2(20 BYTE) NOT NULL, 
	"BANCO_ID" NUMBER NOT NULL, 
	"USUARIO_ID" NUMBER NOT NULL, 
	"SALDO" FLOAT(126) DEFAULT 0 NOT NULL, 
    PRIMARY KEY("ID")
);

CREATE TABLE "BANCO"."MOVIMIENTO" (	
	"ID" NUMBER NOT NULL, 
	"CUENTA_ID" NUMBER NOT NULL, 
	"FECHA" DATE NOT NULL, 
	"SALDO_ANTERIOR" FLOAT(126) NOT NULL, 
	"SALDO_NUEVO" FLOAT(126) NOT NULL, 
	"MONTO" FLOAT(126) NOT NULL, 
	"TIPO_MOVIMIENTO" VARCHAR2(20 BYTE) NOT NULL, 
    PRIMARY KEY("ID")
);

alter table CUENTA
  add constraint FK_CUENTA_BANCO
  foreign key (BANCO_ID)
  references BANCO (ID);
  
alter table CUENTA
  add constraint FK_CUENTA_USUARIO
  foreign key (USUARIO_ID)
  references USUARIO(ID);

alter table MOVIMIENTO
  add constraint FK_MOVIMIENTO_CUENTA
  foreign key (CUENTA_ID)
  references CUENTA(ID);


CREATE SEQUENCE "BANCO"."BAN_SEQ" 
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1
    NOORDER NOCYCLE;
    
    create or replace TRIGGER ban_bir 
BEFORE INSERT ON BANCO 
FOR EACH ROW

BEGIN
  SELECT ban_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;


CREATE SEQUENCE "BANCO"."CUE_SEQ" 
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1
    NOORDER NOCYCLE;
    
    create or replace TRIGGER cue_bir 
BEFORE INSERT ON CUENTA 
FOR EACH ROW

BEGIN
  SELECT cue_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;



CREATE SEQUENCE "BANCO"."MOV_SEQ" 
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1
    NOORDER NOCYCLE;
    
    create or replace TRIGGER usu_bir 
BEFORE INSERT ON MOVIMIENTO 
FOR EACH ROW

BEGIN
  SELECT mov_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;


CREATE SEQUENCE "BANCO"."USU_SEQ" 
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1
    NOORDER NOCYCLE;
    
    create or replace TRIGGER usu_bir 
BEFORE INSERT ON USUARIO 
FOR EACH ROW

BEGIN
  SELECT usu_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
>>>>>>> 56a3c87fb77f2aff69f21b398b20ea4ec97d7995
END;